# Generated by Django 6.0.7 on 2026-08-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0008_devolucion_con_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='origen_offline_id',
            field=models.UUIDField(blank=True, help_text='Identificador generado en el teléfono al capturar esta encuesta sin conexión. Vacío en las encuestas creadas online.', null=True, unique=True, verbose_name='identificador de captura offline'),
        ),
    ]
